const Authentication = {
  LOADED_APP: 'LOAD_APP',
  LOGGED_IN: 'LOGGED_IN',
  LOGGED_IN_ERROR: 'LOGGED_IN_ERROR',
  REGISTER_DEVICE: 'REGISTER_DEVICE',
  REGISTER_DEVICE_ERROR: 'REGISTER_DEVICE_ERROR',
  LOGGED_OUT: 'LOGGED_OUT',
  LOGGED_OUT_ERROR: 'LOGGED_OUT_ERROR',
  FETCH_DEVICE_INFO: 'FETCH_DEVICE_INFO'
}

const Connection = {
  FETCH_CONNECTION: 'FETCH_CONNECTION',
}

export {
  Authentication,
  Connection,
}